djBasics/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polling/', include('polling.urls')),
    path('admin/', admin.site.urls),
]

polling/urls.py
from django.urls import path

from . import views

app_name = 'polling'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('createpost/', views.PostView.as_view(), name='post'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

polling/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
class Question(models.Model):
    questionText = models.CharField(max_length=250)
    #user = models.ForeignKey(User, on_delete=models.CASCADE)
    publicationDate = models.DateTimeField('date published')
    likes = models.IntegerField(default=0)
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days = 1) <= self.publicationDate <= now
    def __str__(self):
        return self.questionText

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choiceText = models.CharField(max_length=150)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choiceText

class Tag(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    tagText = models.CharField(max_length=20)
    def __str__(self):
        return self.tagText

polling/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic, View
from django.utils import timezone
from django.contrib.auth import authenticate, logout, login
from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password
from .models import Choice, Question

class IndexView(generic.ListView):
    template_name = "polling/index.html"
    context_object_name = "latestQuestions"

    def checkLogIn(self, request):
        # Double checks if the user is signed in, returns bool
        return request.user.is_authenticated

    def post(self, request):
        userLoggedIn = self.checkLogIn(request)
        if userLoggedIn == True:
            if "Like" in request.POST.keys():
                #Gets id of question using hidden input tag name
                id = request.POST.get("questionID")
                #Makes a variable corresponding with the question's ID
                question = get_object_or_404(Question, pk = id)
                #Adds one like to the question and saves
                question.likes += 1
                question.save()
                questions = self.get_queryset()
                return HttpResponseRedirect(reverse('polling:detail', args = (id,)))
            if "Logout" in request.POST.keys():
                # Logs out the user
                logout(request)
                # Obviously sets the check for login to false, since the user just signed out
                userLoggedIn = False
                questions = self.get_queryset()
                return render(request, "polling/index.html", {"latestQuestions": questions, "userLoggedIn": userLoggedIn})
        if "Username" in request.POST.keys():
            print(request.POST.keys())
            if "Login" in request.POST.keys():
                user = authenticate(username = request.POST['Username'], password = request.POST['Password'])
                if user is not None:
                    #print("Logged in successfully")
                    login(request, user)
                else:
                    questions = self.get_queryset()
                    return render(request, 'polling/index.html', {'latestQuestions' : questions, "userLoggedIn": userLoggedIn, 'error_message' : "Cannot find user with login info."})
            if "Register" in request.POST.keys():
                #Makes new user entry and saves it
                newUser = User(username = request.POST['Username'], password = make_password(request.POST['Password']))
                newUser.save()
                login(request, newUser)
            # If the user is logged in, variable is true
            userLoggedIn = self.checkLogIn(request)
            questions = self.get_queryset()
            return render(request, "polling/index.html", {"latestQuestions": questions, "userLoggedIn": userLoggedIn})


    def get(self, request):
        if "Tag" in request.GET.keys():
            # print(request.GET)
            # Finds tag value
            tag = request.GET.get("Tag")
            questions = self.get_queryset(tag)
        else:
            questions = self.get_queryset()
        userLoggedIn = request.user.is_authenticated
        # print("QUESTIONS", questions)
        return render(request, "polling/index.html", {"latestQuestions": questions, "userLoggedIn": userLoggedIn})


    def get_queryset(self, tag = None):
        if tag == None:
            return Question.objects.filter(
                publicationDate__lte=timezone.now()
            ).order_by('publicationDate')[:10]
        else:
            #if there IS a tag, sort using the tag text
            return Question.objects.filter(
                publicationDate__lte=timezone.now()
            ).filter(tag__tagText=tag).order_by('publicationDate')[:10]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polling/detail.html'

    def get_queryset(self):
        # Excludes any questions that aren't published yet.
        return Question.objects.filter(publicationDate__lte=timezone.now())

class PostView(View):
    template_name = 'polling/createPost.html'

    def get(self, request):
        return render(request, self.template_name, {})

    def post(self, request):
        # # Create a new question based on the keys in the request (which come from the template)
        newPost = Question(questionText = request.POST['BodyText'], publicationDate = timezone.now())
        newPost.save()
        # # loop through all option/choice keys and create corresponding choices to question
        # print(request.POST.keys())
        for key in request.POST.keys():
            #Create a new option for every key that has the word "option" (keys are made by template) and sent through form
            if "Option" in key:
                newOption = Choice(question = newPost, choiceText = request.POST[key])
                # print(newOption)
                newOption.save()
            # print(newPost)
        #sends the user to the detail view/template of the newly created question/post
        return HttpResponseRedirect(reverse('polling:detail', args = (newPost.id,)))


    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(publicationDate__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polling/results.html'

def vote(request, question_id):
    # Get the question ID
    question = get_object_or_404(Question, pk = question_id)
    try:
        # Gets the selected choice
        selected_choice = question.choice_set.get(pk = request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Returns with error message if no answer is selected
        return render(request, 'polling/detail.html', {'question' : question, 'error_message' : "No answer was selected."})
    else:
        # Otherwise, add one to the votes and send the user to the results screen
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polling:results', args = (question.id,)))

polling/templates/polling/createPost.html
{% load static %}
<script defer type="text/javascript" src="{% static 'polling/createPost.js' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'polling/style.css' %}">
<div class="VoteDiv">
  <h1>Create Post</h1>
  <form method="POST">
    {% csrf_token %}
    <textarea class="InputTextArea" name = "BodyText" placeholder="Body Text" rows="3" style="width:100%"></textarea>
    <hr></hr>
    <h2>Create Choices</h2>
    <a id = "NewChoice" onclick="createNewChoice()">+ Choice</a>
    <div id ="NewChoiceDiv">
    </div>
    <hr></hr>
    <div class="Space">
      <p>Only approved posts can have tags. This is so that searchable posts cannot contain specific material. Read our site's rules for more information.</p>
      <input type="submit" id="MajorButton" name="Submit" value="Submit"></input>
      <a href = "{% url 'polling:index'%}">Return to Feed</a>
    </div>
  </form>
</div>

polling/templates/polling/detail.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polling/style.css' %}">
<div class="VoteDiv">
  <form method="GET">
    <div class="TagDiv">
      {% for tag in question.tag_set.all %}
      <input type= "submit" class = "Tag" name = "Tag" value = "{{tag.tagText}}"></input>
      {% endfor %}
    </div>
  </form>
  <h1>{{ question.questionText }}</h1>
  <input type="submit" class="LikeButton" name="Like" value="Like {{question.likes}}"></input>
  {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
  <form action="{% url 'polling:vote' question.id %}" method="post">
  {% csrf_token %}
  {% for choice in question.choice_set.all %}
      <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
      <label for="choice{{ forloop.counter }}">{{ choice.choiceText }}</label><br>
  {% endfor %}
  <hr></hr>
  <input type="submit" id="MajorButton" value="Vote">
  <a href = "{% url 'polling:index'%}">Return to Feed</a>
  </form>
</div>

polling/templates/polling/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polling/style.css' %}">
<div class="TitleBar">
  <img class="PolarIcon" alt="Polar Icon" src="../../static/polling/images/polarIcon.png" width="200em" style="padding: 0.5em">
  <hr></hr>
  {% if userLoggedIn %}
    <p>Make your vote count <em>{{user.username}}</em>!</p>
    <a href="{% url 'polling:post' %}"><button href="{% url 'polling:post' %}">Create New Post</button></a>
    <form method="POST">
      {% csrf_token %}
      <input type="submit" class="LoginButton" name = "Logout" value = "Logout"></input>
    </form>
  {% else %}
    <p>You are not logged in. Please log in to post or like polls.</p>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <form method="POST">
      {% csrf_token %}
      <input type="text" name = "Username" placeholder="Username"></input>
      <input type="password" name = "Password" placeholder="Password"></input>
      <input type="submit" class="LoginButton" name = "Login" value = "Login"></input>
      <input type="submit" class="LoginButton" name = "Register" value = "Register"></input>
    </form>
  {% endif %}
</div>
<div class="MainFeed">
  {% if latestQuestions %}
      <ul>
      {% for question in latestQuestions %}
        <div class="PollDiv">
          <h2>{{question.questionText}}</h2>
          <form method="GET">
            <div class="TagDiv">
              {% for tag in question.tag_set.all %}
              <input type= "submit" class = "Tag" name = "Tag" value = "{{tag.tagText}}"></input>
              {% endfor %}
            </div>
          </form>
          <hr></hr>
          <form method="POST">
            {% csrf_token %}
            <input type="submit" class="LikeButton" name = "Like" value = "Like {{question.likes}}"></input>
            <input type="hidden" name="questionID" value={{question.id}}></input>
          </form>
          <a href="{% url 'polling:detail' question.id %}"><button href="{% url 'polling:detail' question.id %}">&#129154;</button></a>
        </div>
      {% endfor %}
      </ul>
  {% else %}
      <p>No polls are available.</p>
  {% endif %}
</div>

polling/templates/polling/results.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polling/style.css' %}">
<div class="VoteDiv">
  <h1>{{ question.questionText}}</h1>
  <input type="submit" class="LikeButton" name="Like" value="Like {{question.likes}}""></input>
  {% for choice in question.choice_set.all %}
    <p>{{ choice.choiceText}} -- {{choice.votes}} vote{{ choice.votes|pluralize}} </p>
  {% endfor %}
  <hr></hr>
  <div class="Space">
    <a href = "{% url 'polling:detail' question.id %}">Vote Again</a>
    <a href = "{% url 'polling:index'%}">Return to Feed</a>
  </div>
</div>